server:
  port: 5060  #服务端口
  servlet:
    context-path: /eureka
spring:
  application:
    name: eureka-server
eureka:
  client:
    fetch-registry: false #是否检索服务
    register-with-eureka: true #是否向Eureka注册服务
    service-url:
    #设置与EurekaServer交互的地址，查询服务和注册服务都需要依赖这个地址。
      defaultZone: http://localhost:5060/eureka/eureka
  instance:
    hostname: localhost #设置主机名
  server:
    #是否开启自我保护模式
    enable-self-preservation: false
      #扫描失效服务的间隔时间(单位是毫秒，摩恩是60*1000)，即60s
      #指定EvictionTask定时任务的调度频率，用于剔除过期的实例
    eviction-interval-timer-in-ms: 10000
